"""기초: 변수, 타입, 연산자"""

QUIZZES = [
    {
        "id": "basics_01",
        "concept": "변수 타입",
        "code": 'x = 3\ny = "3"\nprint(type(x) == type(y))',
        "choices": ["A. True", "B. False", "C. 3", "D. 에러"],
        "answer": "B",
        "explanation": "x는 int, y는 str이므로 타입이 다릅니다.",
    },
    {
        "id": "basics_02",
        "concept": "정수 나눗셈",
        "code": "print(7 // 2, 7 % 2)",
        "choices": ["A. 3.5 1", "B. 3 1", "C. 3 0", "D. 4 1"],
        "answer": "B",
        "explanation": "//는 몫(3), %는 나머지(1)를 반환합니다.",
    },
    {
        "id": "basics_03",
        "concept": "문자열 반복",
        "code": 'print("ha" * 3)',
        "choices": ['A. ha3', 'B. hahaha', 'C. ha ha ha', 'D. 에러'],
        "answer": "B",
        "explanation": "문자열 * 정수는 문자열을 반복합니다.",
    },
    {
        "id": "basics_04",
        "concept": "타입 변환",
        "code": 'x = "10"\ny = 5\nprint(int(x) + y)',
        "choices": ["A. 105", "B. 15", "C. 에러", "D. '15'"],
        "answer": "B",
        "explanation": "int('10')은 정수 10이 되어 10 + 5 = 15입니다.",
    },
    {
        "id": "basics_05",
        "concept": "비교 연산자",
        "code": "print(1 == True, 0 == False)",
        "choices": ["A. True True", "B. False False", "C. True False", "D. False True"],
        "answer": "A",
        "explanation": "Python에서 True는 1, False는 0과 같습니다.",
    },
    {
        "id": "basics_06",
        "concept": "multiple assignment",
        "code": "a, b, c = 1, 2, 3\na, b = b, a\nprint(a, b, c)",
        "choices": ["A. 1 2 3", "B. 2 1 3", "C. 3 2 1", "D. 에러"],
        "answer": "B",
        "explanation": "a, b = b, a는 두 변수의 값을 swap합니다.",
    },
    {
        "id": "basics_07",
        "concept": "f-string",
        "code": 'x = 3\nprint(f"{x:05d}")',
        "choices": ["A. 3", "B. 00003", "C. 30000", "D. 에러"],
        "answer": "B",
        "explanation": ":05d는 5자리로 맞추고 빈 자리를 0으로 채웁니다.",
    },
    {
        "id": "basics_08",
        "concept": "None 비교",
        "code": "x = None\nprint(x is None, x == 0, x == False)",
        "choices": [
            "A. True False False",
            "B. True True True",
            "C. True True False",
            "D. False False False",
        ],
        "answer": "A",
        "explanation": "None은 0이나 False와 다릅니다. is None으로 비교하세요.",
    },
    {
        "id": "basics_09",
        "concept": "거듭제곱",
        "code": "print(2 ** 10)",
        "choices": ["A. 20", "B. 100", "C. 1024", "D. 512"],
        "answer": "C",
        "explanation": "**는 거듭제곱 연산자입니다. 2^10 = 1024.",
    },
    {
        "id": "basics_10",
        "concept": "walrus operator",
        "code": 'if (n := 10) > 5:\n    print(n)',
        "choices": ["A. True", "B. 10", "C. 5", "D. 에러"],
        "answer": "B",
        "explanation": ":= (walrus)는 값을 할당하면서 동시에 표현식으로 사용합니다.",
    },
]
