"""딕셔너리: 조작, 메서드, 순회"""

QUIZZES = [
    {
        "id": "dicts_01",
        "concept": "get 기본값",
        "code": 'd = {"a": 1, "b": 2}\nprint(d.get("c", 0))',
        "choices": ["A. None", "B. 0", "C. 에러", "D. c"],
        "answer": "B",
        "explanation": "get()은 키가 없으면 두 번째 인자(기본값)를 반환합니다.",
    },
    {
        "id": "dicts_02",
        "concept": "keys/values",
        "code": 'd = {"x": 1, "y": 2, "z": 3}\nprint(list(d.values()))',
        "choices": ["A. [x, y, z]", "B. [1, 2, 3]", "C. [(x,1), (y,2)]", "D. 에러"],
        "answer": "B",
        "explanation": "values()는 값만 반환합니다.",
    },
    {
        "id": "dicts_03",
        "concept": "dict comprehension",
        "code": "d = {x: x**2 for x in range(4)}\nprint(d)",
        "choices": [
            "A. {0: 0, 1: 1, 2: 4, 3: 9}",
            "B. {1: 1, 2: 4, 3: 9}",
            "C. [0, 1, 4, 9]",
            "D. 에러",
        ],
        "answer": "A",
        "explanation": "range(4)는 0~3이고, 각 값의 제곱이 value가 됩니다.",
    },
    {
        "id": "dicts_04",
        "concept": "update",
        "code": 'a = {"x": 1}\na.update({"x": 10, "y": 20})\nprint(a)',
        "choices": [
            "A. {'x': 1, 'y': 20}",
            "B. {'x': 10, 'y': 20}",
            "C. {'x': 1}",
            "D. 에러",
        ],
        "answer": "B",
        "explanation": "update는 기존 키를 덮어쓰고 새 키를 추가합니다.",
    },
    {
        "id": "dicts_05",
        "concept": "del & pop",
        "code": 'd = {"a": 1, "b": 2, "c": 3}\nval = d.pop("b")\nprint(len(d), val)',
        "choices": ["A. 3 2", "B. 2 2", "C. 2 b", "D. 에러"],
        "answer": "B",
        "explanation": "pop은 키를 제거하고 값을 반환합니다. 남은 키 2개.",
    },
    {
        "id": "dicts_06",
        "concept": "in 연산자 (딕셔너리)",
        "code": 'd = {"a": 1, "b": 2}\nprint("a" in d, 1 in d)',
        "choices": [
            "A. True True",
            "B. True False",
            "C. False True",
            "D. False False",
        ],
        "answer": "B",
        "explanation": "in은 키만 검사합니다. 값을 찾으려면 in d.values().",
    },
    {
        "id": "dicts_07",
        "concept": "setdefault",
        "code": 'd = {"a": 1}\nd.setdefault("a", 99)\nd.setdefault("b", 99)\nprint(d)',
        "choices": [
            "A. {'a': 99, 'b': 99}",
            "B. {'a': 1, 'b': 99}",
            "C. {'a': 1}",
            "D. 에러",
        ],
        "answer": "B",
        "explanation": "setdefault는 키가 없을 때만 값을 설정합니다.",
    },
    {
        "id": "dicts_08",
        "concept": "딕셔너리 언패킹",
        "code": 'a = {"x": 1}\nb = {"y": 2}\nc = {**a, **b, "z": 3}\nprint(c)',
        "choices": [
            "A. {'x': 1, 'y': 2, 'z': 3}",
            "B. {'z': 3}",
            "C. {**a, **b, 'z': 3}",
            "D. 에러",
        ],
        "answer": "A",
        "explanation": "**는 딕셔너리를 풀어서 합칩니다.",
    },
    {
        "id": "dicts_09",
        "concept": "items 순회",
        "code": 'd = {"a": 1, "b": 2}\nfor k, v in d.items():\n    print(k, end="")',
        "choices": ["A. 12", "B. ab", "C. a1b2", "D. ('a',1)('b',2)"],
        "answer": "B",
        "explanation": "items()는 (key, value) 쌍을 반환하지만 k만 출력했습니다.",
    },
    {
        "id": "dicts_10",
        "concept": "fromkeys",
        "code": 'd = dict.fromkeys(["a", "b", "c"], 0)\nprint(d)',
        "choices": [
            "A. {'a': 0, 'b': 0, 'c': 0}",
            "B. {0: ['a','b','c']}",
            "C. [('a',0), ('b',0)]",
            "D. 에러",
        ],
        "answer": "A",
        "explanation": "fromkeys는 키 리스트로 딕셔너리를 만들고 모두 같은 값으로 초기화합니다.",
    },
]
