"""리스트: 인덱싱, 슬라이싱, 메서드"""

QUIZZES = [
    {
        "id": "lists_01",
        "concept": "슬라이싱",
        "code": "nums = [10, 20, 30, 40, 50]\nprint(nums[1:4])",
        "choices": ["A. [10, 20, 30]", "B. [20, 30, 40]", "C. [20, 30, 40, 50]", "D. [10, 20, 30, 40]"],
        "answer": "B",
        "explanation": "[1:4]는 인덱스 1부터 3까지(4 미포함)입니다.",
    },
    {
        "id": "lists_02",
        "concept": "역순 슬라이싱",
        "code": "nums = [1, 2, 3, 4, 5]\nprint(nums[::-1])",
        "choices": ["A. [5, 4, 3, 2, 1]", "B. [1, 2, 3, 4, 5]", "C. [5]", "D. 에러"],
        "answer": "A",
        "explanation": "[::-1]은 리스트를 역순으로 복사합니다.",
    },
    {
        "id": "lists_03",
        "concept": "리스트 연산",
        "code": "print([1, 2] + [3] * 2)",
        "choices": ["A. [1, 2, 3, 3]", "B. [1, 2, 6]", "C. [1, 2, 33]", "D. 에러"],
        "answer": "A",
        "explanation": "[3] * 2 = [3, 3]이고 + 로 합칩니다.",
    },
    {
        "id": "lists_04",
        "concept": "sort vs sorted",
        "code": "a = [3, 1, 2]\nb = sorted(a)\nprint(a, b)",
        "choices": [
            "A. [1, 2, 3] [1, 2, 3]",
            "B. [3, 1, 2] [1, 2, 3]",
            "C. [3, 1, 2] [3, 1, 2]",
            "D. 에러",
        ],
        "answer": "B",
        "explanation": "sorted()는 새 리스트를 반환하고 원본은 변경하지 않습니다.",
    },
    {
        "id": "lists_05",
        "concept": "음수 인덱스",
        "code": "x = [10, 20, 30, 40]\nprint(x[-2])",
        "choices": ["A. 20", "B. 30", "C. 40", "D. 에러"],
        "answer": "B",
        "explanation": "-1이 마지막, -2가 뒤에서 두 번째입니다.",
    },
    {
        "id": "lists_06",
        "concept": "list.pop()",
        "code": "x = [1, 2, 3, 4]\ny = x.pop(1)\nprint(x, y)",
        "choices": [
            "A. [1, 3, 4] 2",
            "B. [2, 3, 4] 1",
            "C. [1, 2, 3] 4",
            "D. [1, 2, 4] 3",
        ],
        "answer": "A",
        "explanation": "pop(1)은 인덱스 1의 원소를 제거하고 반환합니다.",
    },
    {
        "id": "lists_07",
        "concept": "in 연산자",
        "code": "print(3 in [1, 2, 3], 4 in [1, 2, 3])",
        "choices": [
            "A. True True",
            "B. False False",
            "C. True False",
            "D. False True",
        ],
        "answer": "C",
        "explanation": "in은 리스트에 값이 있는지 확인합니다.",
    },
    {
        "id": "lists_08",
        "concept": "enumerate",
        "code": 'for i, v in enumerate(["a", "b", "c"], start=1):\n    print(i, end=" ")',
        "choices": ["A. 0 1 2", "B. 1 2 3", "C. a b c", "D. 에러"],
        "answer": "B",
        "explanation": "enumerate의 start=1은 인덱스를 1부터 시작합니다.",
    },
    {
        "id": "lists_09",
        "concept": "zip",
        "code": "a = [1, 2, 3]\nb = ['x', 'y']\nprint(list(zip(a, b)))",
        "choices": [
            "A. [(1, 'x'), (2, 'y'), (3, None)]",
            "B. [(1, 'x'), (2, 'y')]",
            "C. [1, 'x', 2, 'y']",
            "D. 에러",
        ],
        "answer": "B",
        "explanation": "zip은 짧은 쪽에 맞춰서 짝을 지어줍니다.",
    },
    {
        "id": "lists_10",
        "concept": "얕은 복사",
        "code": "a = [[1, 2], [3, 4]]\nb = a.copy()\nb[0].append(99)\nprint(a[0])",
        "choices": ["A. [1, 2]", "B. [1, 2, 99]", "C. [[1, 2], [3, 4]]", "D. 에러"],
        "answer": "B",
        "explanation": "copy()는 얕은 복사라서 내부 리스트는 같은 객체를 참조합니다.",
    },
]
