"""문자열: 메서드, 포맷팅, 조작"""

QUIZZES = [
    {
        "id": "strings_01",
        "concept": "split & join",
        "code": 'words = "a-b-c".split("-")\nprint(",".join(words))',
        "choices": ["A. a-b-c", "B. a,b,c", "C. ['a','b','c']", "D. 에러"],
        "answer": "B",
        "explanation": "split으로 쪼개고 join으로 다른 구분자로 합칩니다.",
    },
    {
        "id": "strings_02",
        "concept": "strip",
        "code": 'print("  hello  ".strip(), len("  hello  ".strip()))',
        "choices": ["A. hello 5", "B.   hello   7", "C. hello 7", "D. hello5"],
        "answer": "A",
        "explanation": "strip()은 양쪽 공백을 제거합니다. 'hello'는 5글자.",
    },
    {
        "id": "strings_03",
        "concept": "replace",
        "code": 'x = "hello world"\nprint(x.replace("l", "L", 1))',
        "choices": ["A. heLLo worLd", "B. heLlo world", "C. heLLo world", "D. hello world"],
        "answer": "B",
        "explanation": "세 번째 인자 1은 최대 치환 횟수입니다. 첫 l만 교체.",
    },
    {
        "id": "strings_04",
        "concept": "문자열 불변성",
        "code": 's = "hello"\ns[0] = "H"\nprint(s)',
        "choices": ["A. Hello", "B. hello", "C. H", "D. 에러"],
        "answer": "D",
        "explanation": "문자열은 immutable입니다. 인덱스로 수정할 수 없습니다.",
    },
    {
        "id": "strings_05",
        "concept": "startswith",
        "code": 'url = "https://example.com"\nprint(url.startswith(("http://", "https://")))',
        "choices": ["A. True", "B. False", "C. https://", "D. 에러"],
        "answer": "A",
        "explanation": "startswith는 튜플을 받아 하나라도 매치되면 True입니다.",
    },
    {
        "id": "strings_06",
        "concept": "count",
        "code": 'print("banana".count("an"))',
        "choices": ["A. 1", "B. 2", "C. 3", "D. 0"],
        "answer": "B",
        "explanation": "'banana'에서 'an'은 위치 1과 3에서 2번 나옵니다.",
    },
    {
        "id": "strings_07",
        "concept": "find",
        "code": 'print("hello".find("z"))',
        "choices": ["A. -1", "B. 0", "C. None", "D. 에러"],
        "answer": "A",
        "explanation": "find는 못 찾으면 -1을 반환합니다 (index()는 에러).",
    },
    {
        "id": "strings_08",
        "concept": "isdigit",
        "code": 'print("123".isdigit(), "12.3".isdigit(), "".isdigit())',
        "choices": [
            "A. True True True",
            "B. True False False",
            "C. True False True",
            "D. True True False",
        ],
        "answer": "B",
        "explanation": "소수점과 빈 문자열은 digit이 아닙니다.",
    },
    {
        "id": "strings_09",
        "concept": "title & capitalize",
        "code": 'print("hello world".title(), "hello world".capitalize())',
        "choices": [
            "A. Hello World Hello World",
            "B. Hello World Hello world",
            "C. Hello world Hello World",
            "D. HELLO WORLD Hello world",
        ],
        "answer": "B",
        "explanation": "title()은 각 단어 첫글자, capitalize()는 문장 첫글자만 대문자.",
    },
    {
        "id": "strings_10",
        "concept": "문자열 곱셈과 비교",
        "code": 'print("abc" < "abd", "abc" < "abcd")',
        "choices": [
            "A. True True",
            "B. True False",
            "C. False True",
            "D. False False",
        ],
        "answer": "A",
        "explanation": "사전순 비교: c < d이고, 짧은 문자열이 더 작습니다.",
    },
]
